export const themeColors = {
  dark: {
    headerBg: '#23272f',
    border: 'none',
    searchBg: '#23272f',
    searchColor: '#fff',
    icon: '#fff',
    avatarBg: '#7265e6',
    text: '#fff',
    contentBg: '#181a20',
    sidebarBg: '#1f1f1f',
    textSecondary: '#888',
    textDesc: '#aaa',
    textDate: '#aaa',
    cardBg: '#23272f',
    cardText: '#fff',
    cardBorder: 'none',
    cardHeadBg: '#23272f',
    cardHeadText: '#fff',
    cardBodyText: '#fff',
    cardBodyBorder: 'none',
  },
  light: {
    headerBg: '#fff',
    border: '#e5e7eb',
    searchBg: '#f5f5f5',
    searchColor: '#23272f',
    icon: '#23272f',
    avatarBg: '#7265e6',
    text: '#23272f',
    contentBg: '#f7f7f7',
    sidebarBg: '#f7f7f7',
    textSecondary: '#555',
    textDesc: '#888',
    textDate: '#888',
    cardBg: '#fff',
    cardText: '#23272f',
    cardBorder: 'none',
    cardHeadBg: '#fff',
    cardHeadText: '#23272f',
    cardBodyText: '#23272f',
    cardBodyBorder: 'none',
  },
}
